name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
    - run: nix build .#ubootVeyronSpeedy
    - run: nix flake check
    - uses: actions/upload-artifact@v4
      with:
        path: result/*
